import apiClient from './client'

export interface CostCenter {
  id: number
  organization_id: number
  parent_id?: number | null
  project_id?: number | null
  code: string
  name: string
  description: string | null
  is_active: boolean
  projects_count?: number
  projects?: { id: number; project_code: string; project_name: string; status: string }[]
  parent?: { id: number; code: string; name: string } | null
  children?: CostCenter[]
  created_at?: string
  updated_at?: string
}

/** Payload for create/update; code is auto-generated by backend (project_code:segment:...) */
export interface CostCenterFormData {
  parent_id?: number | null
  project_id?: number | null
  name: string
  description?: string | null
  is_active?: boolean
}

export interface GetCostCentersParams {
  project_id?: number
  include_inactive?: boolean
  with_projects?: boolean
  tree?: boolean
  per_page?: number
  page?: number
}

export async function getCostCenters(params?: GetCostCentersParams) {
  const p: Record<string, string | number | boolean | undefined> = {}
  if (params?.project_id != null) p.project_id = params.project_id
  if (params?.include_inactive) p.include_inactive = 1
  if (params?.with_projects) p.with_projects = 1
  if (params?.tree) p.tree = 1
  if (params?.per_page != null) p.per_page = params.per_page
  if (params?.page != null) p.page = params.page
  const response = await apiClient.get('/cost-centers', { params: p })
  const body = response.data as { data?: CostCenter[]; meta?: { total: number; current_page: number; last_page: number; per_page: number } }
  return body
}

export async function createCostCenter(data: CostCenterFormData) {
  const response = await apiClient.post('/cost-centers', data)
  const body = response.data as { data?: CostCenter }
  return (body?.data != null ? body.data : response.data) as CostCenter
}

export async function getCostCenter(id: number) {
  const response = await apiClient.get(`/cost-centers/${id}`)
  const body = response.data as { data?: CostCenter }
  return (body?.data != null ? body.data : response.data) as CostCenter
}

export async function updateCostCenter(id: number, data: Partial<CostCenterFormData>) {
  const response = await apiClient.put(`/cost-centers/${id}`, data)
  const body = response.data as { data?: CostCenter }
  return (body?.data != null ? body.data : response.data) as CostCenter
}

export async function deleteCostCenter(id: number) {
  await apiClient.delete(`/cost-centers/${id}`)
}
